Ecommerce/Areas/Admin/Controllers/DashboardController.cs
using Ecommerce.DataAccess.Repositories;
using Ecommerce.Entities.Interfaces;
using Ecommerce.Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Uitilites;

namespace Ecommerce.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class DashboardController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public DashboardController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            ViewBag.Orders = _unitOfWork.OrderHeader.GetAll().Count();
            ViewBag.Categories = _unitOfWork.Category.GetAll().Count();
            ViewBag.Users = _unitOfWork.ApplicationUser.GetAll().Count();
            ViewBag.Products = _unitOfWork.Product.GetAll().Count();

            return View();
        }
    }
}

Ecommerce/Areas/Admin/Controllers/ProductController.cs
using Ecommerce.DataAccess.Data;
using Ecommerce.DataAccess.Repositories;
using Ecommerce.Entities.Interfaces;
using Ecommerce.Entities.Models;
using Ecommerce.Entities.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Ecommerce.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IUnitOfWork unitOfWork , IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        //Index
        public IActionResult Index()
        {
            var products = _unitOfWork.Product.GetAll();
            return View(products);
        }
        public IActionResult GetData()
        {
            var products = _unitOfWork.Product.GetAll(Include: "Category");
            return Json(new {data = products });
        }

        // Create
        public IActionResult Create()
        {
            ProductVM prouctVM = new ProductVM()
            {
                product = new Product(),
                categoryList = _unitOfWork.Category.GetAll().Select(C => new SelectListItem{
                     Text = C.Name, Value = C.Id.ToString(),
                }),
            };
            return View(prouctVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProductVM productVM, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string RootPath = _webHostEnvironment.WebRootPath;

                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var Upload = Path.Combine(RootPath, "Images", "Products");
                    var ext = Path.GetExtension(file.FileName);

                    if (!Directory.Exists(Upload))
                    {
                        Directory.CreateDirectory(Upload);
                    }

                    using (var filestream = new FileStream(Path.Combine(Upload, fileName + ext), FileMode.Create))
                    {
                        file.CopyTo(filestream);
                    }

                    productVM.product.Img = "Images/Products/" + fileName + ext;
                }

                _unitOfWork.Product.Add(productVM.product);
                _unitOfWork.Complete();
                TempData["Create"] = "Product Has Created Successfully";
                return RedirectToAction(nameof(Index));
            }

            return View(productVM.product);
        }


        //details 
        public IActionResult Details([FromRoute] int? id)
        {
            if (id is null)
            {
                return BadRequest();
            }
            var product = _unitOfWork.Product.GetFirstOrDefault(c => c.Id == id, Include: "Category");
            product.Category = _unitOfWork.Category.GetFirstOrDefault(c=> c.Id == product.CategoryId);
            if (product is null)
            {
                return NotFound();
            }
            return View(product);
        }
        // Update 
        public IActionResult Update([FromRoute] int? id)
        {
            if (id is null)
            {
                return BadRequest();
            }
            ProductVM productVM = new ProductVM()
            {
                product = _unitOfWork.Product.GetFirstOrDefault(c => c.Id == id),
                categoryList = _unitOfWork.Category.GetAll().Select(c => new SelectListItem { Text = c.Name, Value = c.Id.ToString() })
            };
            if (productVM is null)
            {
                return NotFound();
            }
            return View(productVM); 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(ProductVM productVM , IFormFile? file )
        {
            if (ModelState.IsValid)
            {
                string RootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var Upload = Path.Combine(RootPath, @"Images\Products");
                    var ext = Path.GetExtension(file.FileName);

                    if (productVM.product.Img  != null)
                    {
                        var oldImg = Path.Combine(RootPath , productVM.product.Img.TrimStart('\\'));
                        if(System.IO.File.Exists(oldImg))
                        {
                            System.IO.File.Delete(oldImg);
                        }
                    }

                    using (var filestream = new FileStream(Path.Combine(Upload, fileName + ext), FileMode.Create))
                    {
                        file.CopyTo(filestream);
                    }
                    productVM.product.Img = @"Images\Products\" + fileName + ext;
                }

                _unitOfWork.Product.Update(productVM.product);
                _unitOfWork.Complete();
                TempData["Update"] = "Product Has Updated Successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(productVM.product);
        }
        //Delete
        [HttpDelete]
        public IActionResult Delete([FromRoute] int? id)
        {
            if (id is null)
            {
                return BadRequest();
            }
            var product = _unitOfWork.Product.GetFirstOrDefault((c => c.Id == id));
            if (product is null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            _unitOfWork.Product.Remove(product);
            var oldImg = Path.Combine(_webHostEnvironment.WebRootPath, product.Img.TrimStart('\\'));
            if (System.IO.File.Exists(oldImg))
            {
                System.IO.File.Delete(oldImg);
            }
            _unitOfWork.Complete();
            return Json(new { success = true, message = "File has Been Deleted" });
        }

    }
}

Ecommerce/Areas/Customer/Controllers/CartController.cs
using Ecommerce.Entities.Interfaces;
using Ecommerce.Entities.Models;
using Ecommerce.Entities.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe.BillingPortal;
using Stripe.Checkout;
using Stripe.FinancialConnections;
using System.Security.Claims;
using Uitilites;
using Session = Stripe.Checkout.Session;
using SessionCreateOptions = Stripe.Checkout.SessionCreateOptions;
using SessionService = Stripe.Checkout.SessionService;

namespace Ecommerce.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class CartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ShoppingCartVM shoppingCartVm { get; set; }
        public int TotalCarts { get; set; }
        public CartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            shoppingCartVm = new ShoppingCartVM()
            {
                CartList = _unitOfWork.ShoppingCart.GetAll(sc => sc.ApplicationUserId == claim.Value, Include: "Product")
            };

            foreach (var item in shoppingCartVm.CartList)
            {
                shoppingCartVm.TotalCarts += (item.Count * item.Product.Price);
            }
            return View(shoppingCartVm);
        }
        public IActionResult Minus(int cartid)
        {
            var shoppingcart = _unitOfWork.ShoppingCart.GetFirstOrDefault(sc => sc.Id == cartid);
            if (shoppingcart.Count <= 1)
            {
                _unitOfWork.ShoppingCart.Remove(shoppingcart);
                var count = _unitOfWork.ShoppingCart.GetAll(x => x.ApplicationUserId == shoppingcart.ApplicationUserId).ToList().Count() - 1;
                HttpContext.Session.SetInt32(SD.SessionKey, count);
                _unitOfWork.Complete();
                return RedirectToAction("Index","Home");
            }
            else
            {
                _unitOfWork.ShoppingCart.DecreaseCount(shoppingcart, 1);
                _unitOfWork.Complete();
                return RedirectToAction("Index");
            }

        }
        public IActionResult Plus(int cartid)
        {
            var shoppingcart = _unitOfWork.ShoppingCart.GetFirstOrDefault(sc => sc.Id == cartid);
            _unitOfWork.ShoppingCart.IncreaseCount(shoppingcart, 1);
            _unitOfWork.Complete();
            return RedirectToAction("Index");
        }
        public IActionResult Remove(int cartid)
        {
            var shoppingcart = _unitOfWork.ShoppingCart.GetFirstOrDefault(sc => sc.Id == cartid);
            _unitOfWork.ShoppingCart.Remove(shoppingcart);
            _unitOfWork.Complete();
            var count = _unitOfWork.ShoppingCart.GetAll(x => x.ApplicationUserId == shoppingcart.ApplicationUserId).ToList().Count();
            HttpContext.Session.SetInt32(SD.SessionKey, count);
            int numberofunits = _unitOfWork.ShoppingCart.CountItems();
            if (numberofunits > 1)
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index");
        }
        public IActionResult Summary()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
             shoppingCartVm = new ShoppingCartVM()
            {
                CartList = _unitOfWork.ShoppingCart.GetAll(sc => sc.ApplicationUserId == claim.Value, Include: "Product"),
                OrderHeader = new()
            };
            shoppingCartVm.OrderHeader.ApplicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(ap => ap.Id == claim.Value);
            shoppingCartVm.OrderHeader.Name = shoppingCartVm.OrderHeader.ApplicationUser.Name;
            shoppingCartVm.OrderHeader.Address = shoppingCartVm.OrderHeader.ApplicationUser.Adress;
            shoppingCartVm.OrderHeader.City = shoppingCartVm.OrderHeader.ApplicationUser.City;
            shoppingCartVm.OrderHeader.Phone = shoppingCartVm.OrderHeader.ApplicationUser.PhoneNumber;
            foreach (var item in shoppingCartVm.CartList)
            {
                shoppingCartVm.TotalCarts += (item.Count * item.Product.Price);
            }
                return View(shoppingCartVm);
        }
          

        [HttpPost]
        [ActionName("Summary")]
        [ValidateAntiForgeryToken]
        public IActionResult Summary(ShoppingCartVM shoppingCartVM)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            shoppingCartVM.CartList = _unitOfWork.ShoppingCart.GetAll(sc => sc.ApplicationUserId == claim.Value, Include: "Product");
            
            shoppingCartVM.OrderHeader.OrderStatus = "Pinding";
            shoppingCartVM.OrderHeader.PaymentStatus = "Pinding";
            shoppingCartVM.OrderHeader.OrderDate = DateTime.Now;
            shoppingCartVM.OrderHeader.ApplicationUserId = claim.Value;
            foreach (var item in shoppingCartVM.CartList)
            {
                shoppingCartVM.TotalCarts += (item.Count * item.Product.Price);
            }
            shoppingCartVM.OrderHeader.TotalPrice = shoppingCartVM.TotalCarts;
			_unitOfWork.OrderHeader.Add(shoppingCartVM.OrderHeader);
            _unitOfWork.Complete();


            //useStrip
           
            var domain = "http://localhost:7121/";
            var options = new SessionCreateOptions
            {
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment",
                SuccessUrl = $"https://localhost:7121/customer/cart/orderconfirmation?id={shoppingCartVM.OrderHeader.Id}",
                CancelUrl = $"https://localhost:7121/customer/cart/index"
            };
            
            foreach (var item in shoppingCartVM.CartList) {
                var sessionlineoption = new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = (long)(item.Product.Price*100),
                        Currency = "usd",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = item.Product.Name,
                        },
                    },
                    Quantity = item.Count,
                };
                options.LineItems.Add(sessionlineoption);
            }

            var service = new SessionService();
            Session session = service.Create(options);
            shoppingCartVM.OrderHeader.SessionId = session.Id;

            _unitOfWork.Complete();

            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);
        }

        public IActionResult OrderConfirmation(int id ) { 
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(oh=>oh.Id == id);
            var service = new SessionService();
            Session session = service.Get(orderHeader.SessionId);

            if (session.PaymentStatus.ToLower() == "paid")
            {
                _unitOfWork.OrderHeader.UpdateOrderStatus(id, SD.Approve, SD.Approve);
                orderHeader.PaymentIntentId = session.PaymentIntentId;
                _unitOfWork.Complete();
            }
            List<ShoppingCart> shoppingCarts = _unitOfWork.ShoppingCart.GetAll(u=>u.ApplicationUserId == orderHeader.ApplicationUserId).ToList();
            _unitOfWork.ShoppingCart.RemoveRange(shoppingCarts);
            _unitOfWork.Complete();
            return View(id);
        }

    }
}

Ecommerce/Views/Shared/_Dashboard.cshtml
<!DOCTYPE html>
<html lang="en">
<!--begin::Head-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>@ViewBag.CardTitle</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="title" content="AdminLTE 4 | Fixed Sidebar">
    <link href="~/css/adminlte.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
    <link href="~/plugins/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/overlayscrollbars@2.3.0/styles/overlayscrollbars.min.css" integrity="sha256-dSokZseQNT08wYEWiz5iLI8QPlKxG+TswNRD8k35cpg=" crossorigin="anonymous">
    <link href="~/lib/toastr.js/toastr.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/jquery.datatables.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<!--end::Head-->
<!--begin::Body-->
<body class="layout-fixed sidebar-expand-lg bg-body-tertiary" style="padding-bottom:0;margin-bottom:0;">
    <div class="app-wrapper">
        <!-- Header -->
        <nav class="app-header navbar navbar-expand nav-light">
            <div class="container-fluid">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" data-lte-toggle="sidebar" href="#" role="button">
                            <i class="bi bi-list text-secondary"></i>
                        </a>
                    </li>
                    <li class="nav-item d-none d-md-block">
                        <a asp-controller="Home" asp-action="Index" class="nav-link text-secondary">
                            Home
                        </a>
                    </li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </nav>

        <!-- Sidebar -->
        <aside class="app-sidebar bg-body-secondary shadow" data-bs-theme="dark" data-lte-scroll="true">
            <div class="sidebar-brand">
                <!-- Updated Brand link to point to Home -->
                <a asp-controller="Home" asp-action="Index" class="brand-link">
                    <img src="~/assets/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image opacity-75 shadow">
                    <span class="brand-text fw-light">TechXpress-Store</span>
                </a>
            </div>
            <div class="sidebar-wrapper">
                <nav class="mt-2">
                    <ul class="nav sidebar-menu flex-column" data-lte-toggle="treeview" role="menu" data-accordion="false">
                        <li class="nav-item">
                            <a asp-controller="Dashboard" asp-action="Index" class="nav-link">
                                <i class="nav-icon bi bi-speedometer"></i>
                                <p>Admin Dashboard</p>
                            </a>
                        </li>
                        <li class="nav-item text-center">
                            <a asp-controller="Category" asp-action="Index" class="nav-link">
                                <i class="nav-icon bi bi-list"></i>
                                <p>Categories</p>
                            </a>
                        </li>
                        <li class="nav-item text-center">
                            <a asp-controller="Product" asp-action="Index" class="nav-link">
                                <i class="nav-icon bi bi-box-seam"></i>
                                <p>Products</p>
                            </a>
                        </li>
                        <li class="nav-item text-center">
                            <a asp-controller="Order" asp-action="Index" class="nav-link">
                                <i class="nav-icon bi bi-cart"></i>
                                <p>Orders</p>
                            </a>
                        </li>
                        <li class="nav-item text-center">
                            <a asp-controller="Users" asp-action="Index" class="nav-link">
                                <i class="nav-icon bi bi-people"></i>
                                <p>Users</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="Index" class="nav-link">
                                <i class="nav-icon bi bi-person-circle"></i>
                                <p>User Screen</p>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>

        <!-- Main Content -->
        <main class="app-main">
            <div class="app-content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h3 class="mb-3 fw-bold fst-italic">@ViewBag.PageTitle</h3>
                        </div>
                    </div>
                </div>
            </div>
            <div class="app-content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h1 class="card-title my-2 fw-bold fst-italic fs-5 text-primary">@ViewBag.CardTitle</h1>
                                    <div class="card-tools">
                                        <button type="button" class="btn btn-tool" data-lte-toggle="card-collapse" title="Collapse">
                                            <i data-lte-icon="expand" class="bi bi-plus-lg"></i>
                                            <i data-lte-icon="collapse" class="bi bi-dash-lg"></i>
                                        </button>
                                        <button type="button" class="btn btn-tool" data-lte-toggle="card-remove" title="Remove">
                                            <i class="bi bi-x-lg"></i>
                                        </button>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <partial name="_Toasters" />
                                    @RenderBody()
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>

        <!-- Footer -->
        <footer class="app-footer">
            <div class="float-end d-none d-sm-inline">Depi Team</div>
            <strong>
                Copyright &copy; 2014-2024&nbsp;
                <a href="https://adminlte.io" class="text-decoration-none">Depi Team</a>.
            </strong>
            All rights reserved.
        </footer>
    </div>

    <!-- Scripts -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="~/js/adminlte.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/overlayscrollbars/browser/overlayscrollbars.browser.es6.min.js"></script>
    <script src="~/lib/datatables/js/jquery.datatables.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
<!--end::Body-->
</html>

Ecommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ecommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ecommerce.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-dark bg-dark navbar-expand-xl sticky-top shadow-sm">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ecommerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*    <footer class="border-top footer text-muted">
    <div class="container">
    &copy; 2024 - Ecommerce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Ecommerce/Views/Shared/_Toasters.cshtml
@if (TempData["Create"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr["success"]("@TempData["Create"]")
        </script>
}
@if (TempData["Update"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr["info"]("@TempData["Update"]")
    </script>
}
@if (TempData["Delete"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr["error"]("@TempData["Delete"]")
    </script>
}